print("\n")
print("...rebooting system")
print("\n3 \n \n2 \n \n1 \n") 
print(" ##########")
print("## ^   ^  ##")
print("##   ͜     ##")
print(" ##########")
print("\n")
print("Hello I am Beep, what is your name?")
name = input()
print("\t Hello it is nice to meet you", name)
Health1 = 3
Health2 = 5
print("\n")
name
print("Please can you help me? My Health Level is currently: " + " ♥ "*Health1 )
print("I need to reach Health Level: " + " ♥ "*Health2)
print("\n")
print("My ♥ improves when I process information")
print("\n")
print("How tall are you (in meters)?")
Height = float(input())
print("How much do you weigh (in kilograms)?")
Weight = float(input())
bmi = Weight / (Height*Height)
formattedbmi = format(bmi, ".2f")
print("\t", name, "did you know that your bmi is",formattedbmi,)
print("\n")
print("*Information processed*")
print(" +1 ♥ ")
Health3 = 4
print("Health Level:" + " ♥ "*Health3 )
print("\n")
print(name, "how old are you in years?")
Age = int(input())
TotalAge = Age + 8
print("\t Did you know, our ages combined come to a total of",TotalAge,"years old!")
print("\n")
print("*Information processed*")
print(" +1 ♥ ")
print("Health Level:" + " ♥ "*Health2 )
print("\n")
print("\t Thank you",name,"for helping me reach my maximum Health Level your assisstance has been greatly appreciated!")