def run():
  print("Please enter the number of lives")
  lives = int(input())
  print("Please enter the energy level")
  energy = int(input())
  print("Please enter the shield level")
  shield = int(input())
  print("\n")
  print("Health has been set.")
  print("\n")
  print("lives:" + " ♥ "*lives )
  print("\n")
  print("energy level:" + " ♦ "*energy )
  print("\n")
  print("shield level:" + " ♦ "*shield )